# Generated by Django 6.0.5 on 2026-05-26 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SAP', 'SAP ERP'), ('UTILITY', 'Utility Portal'), ('TRAVEL', 'Corporate Travel Platform')], max_length=50)),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='companies.company')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_sources', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ESGRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('scope', models.CharField(choices=[('Scope 1', 'Scope 1 (Direct Emissions)'), ('Scope 2', 'Scope 2 (Indirect Emissions)'), ('Scope 3', 'Scope 3 (Other Indirect Emissions)')], max_length=20)),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('normalized_unit', models.CharField(blank=True, max_length=50)),
                ('activity_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('FAILED', 'Ingestion Failed'), ('SUSPICIOUS', 'Suspicious Record'), ('APPROVED', 'Approved by Analyst'), ('LOCKED', 'Locked for Audit')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esg_records', to='companies.company')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='records.datasource')),
            ],
        ),
        migrations.CreateModel(
            name='UnitConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_unit', models.CharField(max_length=50)),
                ('normalized_unit', models.CharField(max_length=50)),
                ('multiplier', models.DecimalField(decimal_places=4, max_digits=12)),
            ],
            options={
                'unique_together': {('source_unit', 'normalized_unit')},
            },
        ),
    ]
